hw3
Kabanya/graphics-course pull request #1
Opened 2024-10-21 19:34 UTC by Kabanya

2024-11-16 15:56 UTC, kzubatov commented on tasks/local_shadertoy1/App.cpp
> +        vk::PipelineStageFlagBits2::eTransfer,
лишний пробел

2024-11-16 16:16 UTC, kzubatov commented on tasks/local_shadertoy1/App.cpp
> +      etna::flush_barriers(currentCmdBuf);
Лишний set_state --- при создании descriptor set etna сама сделает смену стейта. НО необходимо записать смену стейта в буфер команд, поэтому:
1.  Убрать set_state для ImageToy
2.  Убрать `etna::flush_barriers(currentCmdBuf);` со строки 148 и поместить между созданием множества дескрипторов и диспатчем

2024-11-16 16:18 UTC, kzubatov commented on tasks/local_shadertoy1/App.cpp
> +          ImageToy.get(), vk::ImageLayout::eTransferSrcOptimal,
Нужно заменить vk::ImageLayout::eGeneral и валидатор перестанет ругаться

2024-11-16 16:19 UTC, kzubatov commented on tasks/local_shadertoy1/shaders/toy.comp
> +    float id;
Нужно определиться с числом пробелов

2024-11-16 16:24 UTC, kzubatov commented on tasks/local_shadertoy1/shaders/toy.comp
> +    vec2 uv = scale * (vec2(fragCoord) / vec2(1280, 720) - vec2(0.5));
Изображение перевернуто, т.к. Vulkan и OGL используют разные системы кординат. Про это можно почитать подробнее здесь: https://www.saschawillems.de/blog/2019/03/29/flipping-the-vulkan-viewport
Для фикса нужно добавить uv.y = -uv.y;

2024-11-16 16:26 UTC, kzubatov commented on tasks/local_shadertoy1/shaders/toy.comp
> +return vec2(minSdf, id);
Нужно форматировать

2024-11-16 16:27 UTC, kzubatov requested changes
Нужно запустить local_shadertoy1 под слоями валидации (debug билд, либо в vulkan configurator выбрать пункт "Layers Controlled by Vulkan Configurator" и в слоях выбрать Validation) и исправить все ошибки, которые выдаст валидация

2024-11-25 17:48 UTC, Kabanya commented on tasks/local_shadertoy1/shaders/toy.comp
> +    vec2 uv = scale * (vec2(fragCoord) / vec2(1280, 720) - vec2(0.5));
Спасибо за комментарии! Залил коммит с исправлениями

2024-12-20 23:56 UTC, closed without merging